export const INCREASE_STROKE = 'INCREASE_STROKE';
export const INCREASE_BIRDIES = 'INCREASE_BIRDIES';
export const INCREASE_STROKE_FOR_ROUND = 'INCREASE_STROKE_FOR_ROUND';
export const ADD_NEW_ROUND = 'ADD_NEW_ROUND';
export const ADD_NEW_HOLE = 'ADD_NEW_HOLE';
